# Generated by Django 3.0.4 on 2020-07-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=40, verbose_name='Enter Your Name')),
                ('your_phone', models.CharField(max_length=17, verbose_name='Telephone Number ex: +90 111 222 33 44')),
                ('your_mail', models.EmailField(max_length=254, verbose_name='Enter Your Email')),
                ('your_address', models.CharField(max_length=40, verbose_name='Enter Your Address')),
                ('schedule_dates', models.CharField(choices=[('Choose Your Scheldule', 'Choose Your Scheldule'), ('9 AM to 10 AM', '9 AM to 10 AM'), ('10 AM to 11 AM', '10 AM to 11 AM'), ('11 AM to 12 PM', '11 AM to 12 PM'), ('1 PM to 2 PM', '1 PM to 2 PM'), ('2 PM to 3 PM', '2 PM to 3 PM'), ('3 PM to 4 PM', '3 PM to 4 PM'), ('4 PM to 5 PM', '4 PM to 5 PM')], default='Choose Your Scheldule', max_length=40)),
                ('your_messagess', models.TextField(verbose_name='Enter Your Message')),
                ('schedule_days', models.CharField(choices=[('Choose Your Day', 'Choose Your Day'), ('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Choose Your Scheldule Day', max_length=35)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=40, verbose_name='Enter Your Name')),
                ('your_mail', models.EmailField(max_length=254, verbose_name='Enter Your Mail')),
                ('your_messagess', models.TextField(verbose_name='Enter Your Message')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
